### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [pgarza917/InstagramClone#1]
It looks like your video walkthrough doesn't seem to show some of the required stories as follows:

1. User can view the last 20 posts submitted to "Instagram"
2. User can pull to refresh the last 20 posts submitted to "Instagram"

Can you update this and resubmit?

**Comment by pgarza917** [comment]
Hi,

Thank you for the feedback on my walkthrough GIF. I have gone ahead and updated the GIF to show the stories that appeared missing in the last GIF. 

For the first feature you mentioned, I made sure to scroll through all 20 posts in the posts fragment a few times throughout the walkthrough. When the user submitted a post, I made sure to scroll through all the posts to show that the last post in the Recycler View changed, as I am only retrieving 20 posts submitted to my app and the previous last post in the Recycler View should now be gone as the new post has kicked it out of the top 20.

For the second feature, I made sure to pull down on the Recycler View for the posts a few times throughout. This is especially apparent when I have a new user named "walkthrough" create a new post. When the post is first created it does not appear in the posts Recycler View. However, when I pull to refresh, the new post appears, and I scroll down to the bottom to show that a post has been kicked out of the top 20 retrieved posts with the new user creating their new post. 

Please let me know if anything else is needed for my submission.

Thanks, Pablo

**Comment by codepathreview** [comment]
Nice work, Pablo. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!
 
/cc @codepathreview
